// Code generated by Slice Machine. DO NOT EDIT.

import type * as prismic from "@prismicio/client";

type Simplify<T> = { [KeyType in keyof T]: T[KeyType] };

type PickContentRelationshipFieldData<
  TRelationship extends
    | prismic.CustomTypeModelFetchCustomTypeLevel1
    | prismic.CustomTypeModelFetchCustomTypeLevel2
    | prismic.CustomTypeModelFetchGroupLevel1
    | prismic.CustomTypeModelFetchGroupLevel2,
  TData extends Record<
    string,
    | prismic.AnyRegularField
    | prismic.GroupField
    | prismic.NestedGroupField
    | prismic.SliceZone
  >,
  TLang extends string,
> =
  // Content relationship fields
  {
    [TSubRelationship in Extract<
      TRelationship["fields"][number],
      prismic.CustomTypeModelFetchContentRelationshipLevel1
    > as TSubRelationship["id"]]: ContentRelationshipFieldWithData<
      TSubRelationship["customtypes"],
      TLang
    >;
  } & // Group
  {
    [TGroup in Extract<
      TRelationship["fields"][number],
      | prismic.CustomTypeModelFetchGroupLevel1
      | prismic.CustomTypeModelFetchGroupLevel2
    > as TGroup["id"]]: TData[TGroup["id"]] extends prismic.GroupField<
      infer TGroupData
    >
      ? prismic.GroupField<
          PickContentRelationshipFieldData<TGroup, TGroupData, TLang>
        >
      : never;
  } & // Other fields
  {
    [TFieldKey in Extract<
      TRelationship["fields"][number],
      string
    >]: TFieldKey extends keyof TData ? TData[TFieldKey] : never;
  };

type ContentRelationshipFieldWithData<
  TCustomType extends
    | readonly (prismic.CustomTypeModelFetchCustomTypeLevel1 | string)[]
    | readonly (prismic.CustomTypeModelFetchCustomTypeLevel2 | string)[],
  TLang extends string = string,
> = {
  [ID in Exclude<
    TCustomType[number],
    string
  >["id"]]: prismic.ContentRelationshipField<
    ID,
    TLang,
    PickContentRelationshipFieldData<
      Extract<TCustomType[number], { id: ID }>,
      Extract<prismic.Content.AllDocumentTypes, { type: ID }>["data"],
      TLang
    >
  >;
}[Exclude<TCustomType[number], string>["id"]];

type BlogDocumentDataSlicesSlice = FaqsSlice | ImageSlice | TextSlice;

/**
 * Content for blog documents
 */
interface BlogDocumentData {
  /**
   * title field in *blog*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: blog.title
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  title: prismic.KeyTextField;

  /**
   * image field in *blog*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: blog.image
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  image: prismic.ImageField<never>;

  /**
   * Slice Zone field in *blog*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: blog.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/slices
   */
  slices: prismic.SliceZone<BlogDocumentDataSlicesSlice> /**
   * Meta Title field in *blog*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: blog.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/fields/text
   */;
  meta_title: prismic.KeyTextField;

  /**
   * Meta Description field in *blog*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: blog.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  meta_description: prismic.KeyTextField;

  /**
   * Meta Image field in *blog*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: blog.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  meta_image: prismic.ImageField<never>;
}

/**
 * blog document from Prismic
 *
 * - **API ID**: `blog`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/content-modeling
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type BlogDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<Simplify<BlogDocumentData>, "blog", Lang>;

/**
 * Item in *childCourses → hero*
 */
export interface ChildcoursesDocumentDataHeroItem {
  /**
   * title field in *childCourses → hero*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: childcourses.hero[].title
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  title: prismic.KeyTextField;

  /**
   * description field in *childCourses → hero*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: childcourses.hero[].description
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  description: prismic.RichTextField;
}

/**
 * Item in *childCourses → related_courses*
 */
export interface ChildcoursesDocumentDataRelatedCoursesItem {
  /**
   * title field in *childCourses → related_courses*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: childcourses.related_courses[].title
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  title: prismic.RichTextField;

  /**
   * image field in *childCourses → related_courses*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: childcourses.related_courses[].image
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  image: prismic.ImageField<never>;
}

/**
 * Item in *childCourses → card_title_des*
 */
export interface ChildcoursesDocumentDataCardTitleDesItem {
  /**
   * title field in *childCourses → card_title_des*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: childcourses.card_title_des[].title
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  title: prismic.KeyTextField;

  /**
   * description field in *childCourses → card_title_des*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: childcourses.card_title_des[].description
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  description: prismic.RichTextField;
}

/**
 * Item in *childCourses → cards*
 */
export interface ChildcoursesDocumentDataCardsItem {
  /**
   * icon field in *childCourses → cards*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: childcourses.cards[].icon
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  icon: prismic.ImageField<never>;

  /**
   * title field in *childCourses → cards*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: childcourses.cards[].title
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  title: prismic.KeyTextField;

  /**
   * description field in *childCourses → cards*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: childcourses.cards[].description
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  description: prismic.RichTextField;
}

/**
 * Item in *childCourses → services_title*
 */
export interface ChildcoursesDocumentDataServicesTitleItem {
  /**
   * title field in *childCourses → services_title*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: childcourses.services_title[].title
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  title: prismic.KeyTextField;
}

/**
 * Item in *childCourses → services_sections*
 */
export interface ChildcoursesDocumentDataServicesSectionsItem {
  /**
   * title field in *childCourses → services_sections*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: childcourses.services_sections[].title
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  title: prismic.KeyTextField;

  /**
   * description field in *childCourses → services_sections*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: childcourses.services_sections[].description
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  description: prismic.RichTextField;

  /**
   * image field in *childCourses → services_sections*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: childcourses.services_sections[].image
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  image: prismic.ImageField<never>;
}

/**
 * Item in *childCourses → structure*
 */
export interface ChildcoursesDocumentDataStructureItem {
  /**
   * title field in *childCourses → structure*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: childcourses.structure[].title
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  title: prismic.KeyTextField;

  /**
   * description field in *childCourses → structure*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: childcourses.structure[].description
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  description: prismic.RichTextField;

  /**
   * image field in *childCourses → structure*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: childcourses.structure[].image
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  image: prismic.ImageField<never>;
}

/**
 * Item in *childCourses → why_choose_us_title_des*
 */
export interface ChildcoursesDocumentDataWhyChooseUsTitleDesItem {
  /**
   * title field in *childCourses → why_choose_us_title_des*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: childcourses.why_choose_us_title_des[].title
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  title: prismic.KeyTextField;
}

/**
 * Item in *childCourses → why_choose_us_cards*
 */
export interface ChildcoursesDocumentDataWhyChooseUsCardsItem {
  /**
   * description field in *childCourses → why_choose_us_cards*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: childcourses.why_choose_us_cards[].description
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  description: prismic.RichTextField;

  /**
   * image field in *childCourses → why_choose_us_cards*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: childcourses.why_choose_us_cards[].image
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  image: prismic.ImageField<never>;
}

/**
 * Item in *childCourses → testimonials*
 */
export interface ChildcoursesDocumentDataTestimonialsItem {
  /**
   * description field in *childCourses → testimonials*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: childcourses.testimonials[].description
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  description: prismic.RichTextField;

  /**
   * name field in *childCourses → testimonials*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: childcourses.testimonials[].name
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  name: prismic.KeyTextField;

  /**
   * address field in *childCourses → testimonials*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: childcourses.testimonials[].address
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  address: prismic.KeyTextField;
}

/**
 * Item in *childCourses → cta*
 */
export interface ChildcoursesDocumentDataCtaItem {
  /**
   * title field in *childCourses → cta*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: childcourses.cta[].title
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  title: prismic.KeyTextField;

  /**
   * description field in *childCourses → cta*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: childcourses.cta[].description
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  description: prismic.RichTextField;

  /**
   * image field in *childCourses → cta*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: childcourses.cta[].image
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  image: prismic.ImageField<never>;
}

/**
 * Item in *childCourses → faqs*
 */
export interface ChildcoursesDocumentDataFaqsItem {
  /**
   * question field in *childCourses → faqs*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: childcourses.faqs[].question
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  question: prismic.KeyTextField;

  /**
   * answer field in *childCourses → faqs*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: childcourses.faqs[].answer
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  answer: prismic.RichTextField;
}

type ChildcoursesDocumentDataSlicesSlice = never;

/**
 * Content for childCourses documents
 */
interface ChildcoursesDocumentData {
  /**
   * category field in *childCourses*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: childcourses.category
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  category: prismic.KeyTextField;

  /**
   * hero field in *childCourses*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: childcourses.hero[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/repeatable-group
   */
  hero: prismic.GroupField<Simplify<ChildcoursesDocumentDataHeroItem>>;

  /**
   * related_courses field in *childCourses*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: childcourses.related_courses[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/repeatable-group
   */
  related_courses: prismic.GroupField<
    Simplify<ChildcoursesDocumentDataRelatedCoursesItem>
  >;

  /**
   * card_title_des field in *childCourses*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: childcourses.card_title_des[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/repeatable-group
   */
  card_title_des: prismic.GroupField<
    Simplify<ChildcoursesDocumentDataCardTitleDesItem>
  >;

  /**
   * cards field in *childCourses*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: childcourses.cards[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/repeatable-group
   */
  cards: prismic.GroupField<Simplify<ChildcoursesDocumentDataCardsItem>>;

  /**
   * services_title field in *childCourses*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: childcourses.services_title[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/repeatable-group
   */
  services_title: prismic.GroupField<
    Simplify<ChildcoursesDocumentDataServicesTitleItem>
  >;

  /**
   * services_sections field in *childCourses*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: childcourses.services_sections[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/repeatable-group
   */
  services_sections: prismic.GroupField<
    Simplify<ChildcoursesDocumentDataServicesSectionsItem>
  >;

  /**
   * structure field in *childCourses*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: childcourses.structure[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/repeatable-group
   */
  structure: prismic.GroupField<
    Simplify<ChildcoursesDocumentDataStructureItem>
  >;

  /**
   * why_choose_us_title_des field in *childCourses*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: childcourses.why_choose_us_title_des[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/repeatable-group
   */
  why_choose_us_title_des: prismic.GroupField<
    Simplify<ChildcoursesDocumentDataWhyChooseUsTitleDesItem>
  >;

  /**
   * why_choose_us_cards field in *childCourses*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: childcourses.why_choose_us_cards[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/repeatable-group
   */
  why_choose_us_cards: prismic.GroupField<
    Simplify<ChildcoursesDocumentDataWhyChooseUsCardsItem>
  >;

  /**
   * testimonials field in *childCourses*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: childcourses.testimonials[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/repeatable-group
   */
  testimonials: prismic.GroupField<
    Simplify<ChildcoursesDocumentDataTestimonialsItem>
  >;

  /**
   * cta field in *childCourses*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: childcourses.cta[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/repeatable-group
   */
  cta: prismic.GroupField<Simplify<ChildcoursesDocumentDataCtaItem>>;

  /**
   * faqs field in *childCourses*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: childcourses.faqs[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/repeatable-group
   */
  faqs: prismic.GroupField<Simplify<ChildcoursesDocumentDataFaqsItem>>;

  /**
   * Slice Zone field in *childCourses*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: childcourses.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/slices
   */
  slices: prismic.SliceZone<ChildcoursesDocumentDataSlicesSlice> /**
   * Meta Title field in *childCourses*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: childcourses.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/fields/text
   */;
  meta_title: prismic.KeyTextField;

  /**
   * Meta Description field in *childCourses*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: childcourses.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  meta_description: prismic.KeyTextField;

  /**
   * Meta Image field in *childCourses*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: childcourses.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  meta_image: prismic.ImageField<never>;
}

/**
 * childCourses document from Prismic
 *
 * - **API ID**: `childcourses`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/content-modeling
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type ChildcoursesDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<
    Simplify<ChildcoursesDocumentData>,
    "childcourses",
    Lang
  >;

/**
 * Item in *mainCourses → hero*
 */
export interface MaincoursesDocumentDataHeroItem {
  /**
   * title field in *mainCourses → hero*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: maincourses.hero[].title
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  title: prismic.KeyTextField;

  /**
   * description field in *mainCourses → hero*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: maincourses.hero[].description
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  description: prismic.RichTextField;

  /**
   * image field in *mainCourses → hero*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: maincourses.hero[].image
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  image: prismic.ImageField<never>;
}

/**
 * Item in *mainCourses → card_title_des*
 */
export interface MaincoursesDocumentDataCardtitledesItem {
  /**
   * title field in *mainCourses → card_title_des*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: maincourses.cardtitledes[].title
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  title: prismic.KeyTextField;

  /**
   * description field in *mainCourses → card_title_des*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: maincourses.cardtitledes[].description
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  description: prismic.RichTextField;
}

/**
 * Item in *mainCourses → cards*
 */
export interface MaincoursesDocumentDataCardsItem {
  /**
   * icon field in *mainCourses → cards*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: maincourses.cards[].icon
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  icon: prismic.ImageField<never>;

  /**
   * title field in *mainCourses → cards*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: maincourses.cards[].title
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  title: prismic.KeyTextField;

  /**
   * description field in *mainCourses → cards*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: maincourses.cards[].description
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  description: prismic.RichTextField;
}

/**
 * Item in *mainCourses → services_title*
 */
export interface MaincoursesDocumentDataServicesTitleItem {
  /**
   * title field in *mainCourses → services_title*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: maincourses.services_title[].title
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  title: prismic.KeyTextField;
}

/**
 * Item in *mainCourses → services_sections*
 */
export interface MaincoursesDocumentDataServicesSectionsItem {
  /**
   * title field in *mainCourses → services_sections*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: maincourses.services_sections[].title
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  title: prismic.KeyTextField;

  /**
   * description field in *mainCourses → services_sections*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: maincourses.services_sections[].description
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  description: prismic.RichTextField;

  /**
   * image field in *mainCourses → services_sections*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: maincourses.services_sections[].image
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  image: prismic.ImageField<never>;

  /**
   * btn field in *mainCourses → services_sections*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: maincourses.services_sections[].btn
   * - **Documentation**: https://prismic.io/docs/fields/link
   */
  btn: prismic.LinkField<string, string, unknown, prismic.FieldState, never>;
}

/**
 * Item in *mainCourses → related_courses*
 */
export interface MaincoursesDocumentDataRelatedCoursesItem {
  /**
   * title field in *mainCourses → related_courses*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: maincourses.related_courses[].title
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  title: prismic.RichTextField;

  /**
   * image field in *mainCourses → related_courses*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: maincourses.related_courses[].image
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  image: prismic.ImageField<never>;
}

/**
 * Item in *mainCourses → why_choose_us_title_des*
 */
export interface MaincoursesDocumentDataWhyChooseUsTitleDesItem {
  /**
   * title field in *mainCourses → why_choose_us_title_des*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: maincourses.why_choose_us_title_des[].title
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  title: prismic.KeyTextField;

  /**
   * description field in *mainCourses → why_choose_us_title_des*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: maincourses.why_choose_us_title_des[].description
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  description: prismic.RichTextField;
}

/**
 * Item in *mainCourses → why_choose_us_cards*
 */
export interface MaincoursesDocumentDataWhyChooseUsCardsItem {
  /**
   * title field in *mainCourses → why_choose_us_cards*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: maincourses.why_choose_us_cards[].title
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  title: prismic.KeyTextField;

  /**
   * description field in *mainCourses → why_choose_us_cards*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: maincourses.why_choose_us_cards[].description
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  description: prismic.RichTextField;

  /**
   * image field in *mainCourses → why_choose_us_cards*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: maincourses.why_choose_us_cards[].image
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  image: prismic.ImageField<never>;
}

/**
 * Item in *mainCourses → testimonials*
 */
export interface MaincoursesDocumentDataTestimonialsItem {
  /**
   * description field in *mainCourses → testimonials*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: maincourses.testimonials[].description
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  description: prismic.RichTextField;

  /**
   * name field in *mainCourses → testimonials*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: maincourses.testimonials[].name
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  name: prismic.KeyTextField;

  /**
   * address field in *mainCourses → testimonials*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: maincourses.testimonials[].address
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  address: prismic.KeyTextField;
}

/**
 * Item in *mainCourses → cta*
 */
export interface MaincoursesDocumentDataCtaItem {
  /**
   * title field in *mainCourses → cta*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: maincourses.cta[].title
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  title: prismic.KeyTextField;

  /**
   * description field in *mainCourses → cta*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: maincourses.cta[].description
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  description: prismic.RichTextField;

  /**
   * image field in *mainCourses → cta*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: maincourses.cta[].image
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  image: prismic.ImageField<never>;
}

/**
 * Item in *mainCourses → faqs*
 */
export interface MaincoursesDocumentDataFaqsItem {
  /**
   * question field in *mainCourses → faqs*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: maincourses.faqs[].question
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  question: prismic.KeyTextField;

  /**
   * answer field in *mainCourses → faqs*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: maincourses.faqs[].answer
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  answer: prismic.RichTextField;
}

type MaincoursesDocumentDataSlicesSlice = never;

/**
 * Content for mainCourses documents
 */
interface MaincoursesDocumentData {
  /**
   * hero field in *mainCourses*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: maincourses.hero[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/repeatable-group
   */
  hero: prismic.GroupField<Simplify<MaincoursesDocumentDataHeroItem>>;

  /**
   * card_title_des field in *mainCourses*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: maincourses.cardtitledes[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/repeatable-group
   */
  cardtitledes: prismic.GroupField<
    Simplify<MaincoursesDocumentDataCardtitledesItem>
  >;

  /**
   * cards field in *mainCourses*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: maincourses.cards[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/repeatable-group
   */
  cards: prismic.GroupField<Simplify<MaincoursesDocumentDataCardsItem>>;

  /**
   * services_title field in *mainCourses*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: maincourses.services_title[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/repeatable-group
   */
  services_title: prismic.GroupField<
    Simplify<MaincoursesDocumentDataServicesTitleItem>
  >;

  /**
   * services_sections field in *mainCourses*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: maincourses.services_sections[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/repeatable-group
   */
  services_sections: prismic.GroupField<
    Simplify<MaincoursesDocumentDataServicesSectionsItem>
  >;

  /**
   * related_courses field in *mainCourses*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: maincourses.related_courses[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/repeatable-group
   */
  related_courses: prismic.GroupField<
    Simplify<MaincoursesDocumentDataRelatedCoursesItem>
  >;

  /**
   * why_choose_us_title_des field in *mainCourses*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: maincourses.why_choose_us_title_des[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/repeatable-group
   */
  why_choose_us_title_des: prismic.GroupField<
    Simplify<MaincoursesDocumentDataWhyChooseUsTitleDesItem>
  >;

  /**
   * why_choose_us_cards field in *mainCourses*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: maincourses.why_choose_us_cards[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/repeatable-group
   */
  why_choose_us_cards: prismic.GroupField<
    Simplify<MaincoursesDocumentDataWhyChooseUsCardsItem>
  >;

  /**
   * testimonials field in *mainCourses*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: maincourses.testimonials[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/repeatable-group
   */
  testimonials: prismic.GroupField<
    Simplify<MaincoursesDocumentDataTestimonialsItem>
  >;

  /**
   * cta field in *mainCourses*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: maincourses.cta[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/repeatable-group
   */
  cta: prismic.GroupField<Simplify<MaincoursesDocumentDataCtaItem>>;

  /**
   * faqs field in *mainCourses*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: maincourses.faqs[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/repeatable-group
   */
  faqs: prismic.GroupField<Simplify<MaincoursesDocumentDataFaqsItem>>;

  /**
   * Slice Zone field in *mainCourses*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: maincourses.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/slices
   */
  slices: prismic.SliceZone<MaincoursesDocumentDataSlicesSlice> /**
   * Meta Title field in *mainCourses*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: maincourses.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/fields/text
   */;
  meta_title: prismic.KeyTextField;

  /**
   * Meta Description field in *mainCourses*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: maincourses.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  meta_description: prismic.KeyTextField;

  /**
   * Meta Image field in *mainCourses*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: maincourses.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  meta_image: prismic.ImageField<never>;
}

/**
 * mainCourses document from Prismic
 *
 * - **API ID**: `maincourses`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/content-modeling
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type MaincoursesDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<
    Simplify<MaincoursesDocumentData>,
    "maincourses",
    Lang
  >;

export type AllDocumentTypes =
  | BlogDocument
  | ChildcoursesDocument
  | MaincoursesDocument;

/**
 * Item in *Faqs → Default → Primary → faqs*
 */
export interface FaqsSliceDefaultPrimaryFaqsItem {
  /**
   * question field in *Faqs → Default → Primary → faqs*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: faqs.default.primary.faqs[].question
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  question: prismic.KeyTextField;

  /**
   * answer field in *Faqs → Default → Primary → faqs*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: faqs.default.primary.faqs[].answer
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  answer: prismic.RichTextField;
}

/**
 * Primary content in *Faqs → Default → Primary*
 */
export interface FaqsSliceDefaultPrimary {
  /**
   * faqs field in *Faqs → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: faqs.default.primary.faqs[]
   * - **Documentation**: https://prismic.io/docs/fields/repeatable-group
   */
  faqs: prismic.GroupField<Simplify<FaqsSliceDefaultPrimaryFaqsItem>>;
}

/**
 * Default variation for Faqs Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type FaqsSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<FaqsSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *Faqs*
 */
type FaqsSliceVariation = FaqsSliceDefault;

/**
 * Faqs Shared Slice
 *
 * - **API ID**: `faqs`
 * - **Description**: Faqs
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type FaqsSlice = prismic.SharedSlice<"faqs", FaqsSliceVariation>;

/**
 * Primary content in *Image → Default → Primary*
 */
export interface ImageSliceDefaultPrimary {
  /**
   * image field in *Image → Default → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: image.default.primary.image
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  image: prismic.ImageField<never>;
}

/**
 * Default variation for Image Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type ImageSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<ImageSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *Image*
 */
type ImageSliceVariation = ImageSliceDefault;

/**
 * Image Shared Slice
 *
 * - **API ID**: `image`
 * - **Description**: Image
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type ImageSlice = prismic.SharedSlice<"image", ImageSliceVariation>;

/**
 * Primary content in *Text → Default → Primary*
 */
export interface TextSliceDefaultPrimary {
  /**
   * text field in *Text → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: text.default.primary.text
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  text: prismic.RichTextField;
}

/**
 * Default variation for Text Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type TextSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<TextSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *Text*
 */
type TextSliceVariation = TextSliceDefault;

/**
 * Text Shared Slice
 *
 * - **API ID**: `text`
 * - **Description**: Text
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type TextSlice = prismic.SharedSlice<"text", TextSliceVariation>;

declare module "@prismicio/client" {
  interface CreateClient {
    (
      repositoryNameOrEndpoint: string,
      options?: prismic.ClientConfig,
    ): prismic.Client<AllDocumentTypes>;
  }

  interface CreateWriteClient {
    (
      repositoryNameOrEndpoint: string,
      options: prismic.WriteClientConfig,
    ): prismic.WriteClient<AllDocumentTypes>;
  }

  interface CreateMigration {
    (): prismic.Migration<AllDocumentTypes>;
  }

  namespace Content {
    export type {
      BlogDocument,
      BlogDocumentData,
      BlogDocumentDataSlicesSlice,
      ChildcoursesDocument,
      ChildcoursesDocumentData,
      ChildcoursesDocumentDataHeroItem,
      ChildcoursesDocumentDataRelatedCoursesItem,
      ChildcoursesDocumentDataCardTitleDesItem,
      ChildcoursesDocumentDataCardsItem,
      ChildcoursesDocumentDataServicesTitleItem,
      ChildcoursesDocumentDataServicesSectionsItem,
      ChildcoursesDocumentDataStructureItem,
      ChildcoursesDocumentDataWhyChooseUsTitleDesItem,
      ChildcoursesDocumentDataWhyChooseUsCardsItem,
      ChildcoursesDocumentDataTestimonialsItem,
      ChildcoursesDocumentDataCtaItem,
      ChildcoursesDocumentDataFaqsItem,
      ChildcoursesDocumentDataSlicesSlice,
      MaincoursesDocument,
      MaincoursesDocumentData,
      MaincoursesDocumentDataHeroItem,
      MaincoursesDocumentDataCardtitledesItem,
      MaincoursesDocumentDataCardsItem,
      MaincoursesDocumentDataServicesTitleItem,
      MaincoursesDocumentDataServicesSectionsItem,
      MaincoursesDocumentDataRelatedCoursesItem,
      MaincoursesDocumentDataWhyChooseUsTitleDesItem,
      MaincoursesDocumentDataWhyChooseUsCardsItem,
      MaincoursesDocumentDataTestimonialsItem,
      MaincoursesDocumentDataCtaItem,
      MaincoursesDocumentDataFaqsItem,
      MaincoursesDocumentDataSlicesSlice,
      AllDocumentTypes,
      FaqsSlice,
      FaqsSliceDefaultPrimaryFaqsItem,
      FaqsSliceDefaultPrimary,
      FaqsSliceVariation,
      FaqsSliceDefault,
      ImageSlice,
      ImageSliceDefaultPrimary,
      ImageSliceVariation,
      ImageSliceDefault,
      TextSlice,
      TextSliceDefaultPrimary,
      TextSliceVariation,
      TextSliceDefault,
    };
  }
}
